export enum AuthResponseCode {
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    TOKEN_MISSING = 'TOKEN_MISSING',
    TOKEN_INVALID = 'TOKEN_INVALID',
    ACCESS_TOKEN_REFRESHED = 'ACCESS_TOKEN_REFRESHED',
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    USER_REGISTERED = 'USER_REGISTERED',
    USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED',
    USER_LOGGED_OUT = 'USER_LOGGED_OUT',
    USER_LOGGED_IN = 'USER_LOGGED_IN',
    USER_ALREADY_LOGGED_IN = 'USER_ALREADY_LOGGED_IN',
    AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
    AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
    SECURITY_TOKEN_REUSED = 'SECURITY_TOKEN_REUSED'

}
