export enum CategoryResponseCode {
    CATEGORY_CREATED = 'CATEGORY_CREATED',
    CATEGORY_UPDATED = 'CATEGORY_UPDATED',
    CATEGORY_DELETED = 'CATEGORY_DELETED',
    CATEGORY_FORBIDDEN = 'CATEGORY_FORBIDDEN',
    CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
    CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
    CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS',
}
