export enum CategoryResponseCode {
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CATEGORY_DELETED = 'CATEGORY_DELETED',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_VALIDATION_FAILED = 'CATEGORY_VALIDATION_FAILED',
  CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS',
  CATEGORY_FETCH_FAILED = 'CATEGORY_FETCH_FAILED',
}
