export enum ItemResponseCode {
    ITEM_CREATED = 'ITEM_CREATED',
    ITEM_FORBIDDEN = 'ITEM_FORBIDDEN',
    ITEM_UPDATED = 'ITEM_UPDATED',
    ITEM_DELETED = 'ITEM_DELETED',
    ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
    ITEM_VALIDATION_FAILED = 'ITEM_VALIDATION_FAILED',
    ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS',
}
