export enum ItemResponseCode {
    ITEM_CREATED = 'ITEM_CREATED',
    ITEM_UPDATED = 'ITEM_UPDATED',
    ITEM_DELETED = 'ITEM_DELETED',
    ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
    ITEM_ALREADY_EXISTS = 'ITEM_ALREADY_EXISTS',
    ITEM_VALIDATION_FAILED = 'ITEM_VALIDATION_FAILED',
    ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS',
    ITEM_FETCH_FAILED = 'ITEM_FETCH_FAILED',
}
