export enum UserResponseCode {
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_VALIDATION_FAILED = 'USER_VALIDATION_FAILED',
    USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS',
    USER_FETCH_FAILED = 'USER_FETCH_FAILED',
    USER_EMAIL_ALREADY_REGISTERED = 'USER_EMAIL_ALREADY_REGISTERED',
}
